### PR TITLE
Hash to scalar

### PR DESCRIPTION
**Pull request by iancoleman**
Draft PR to discuss the pros / cons of this approach.

The motive is to convert any arbitrary bytes to a scalar.

#### Technicalities

This PR is a literal interpretation of
"when hashing to scalars for an elliptic curve (sub)group with prime order r, it suffices to instantiate hash_to_curve with target field GF(r)."
See https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#section-5-4

But there are some further considerations, see the questions at https://crypto.stackexchange.com/questions/94971/choosing-between-bls-sig-keygen-and-hash-to-field

Should `L` stay as 64 or should it be `48`?

Should `DST` stay the same, or replace `G2` with `Fr`, or some other replacement, or empty/blank?

Are there any test vectors that can be added to the tests?

#### Tests

I haven't added any tests for this change in functionality, I'm open to suggestions though.

#### Alternatives

There's a similar idea in bls-sig-keygen

https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-02#section-2.3

It also takes arbitrary bytes and converts to the range `0 <= scalar < CURVE.r`

#### API and style

Is it ok to refer be inconsistent in utils by including it as a one-liner `hashToField: hash_to_field`? Other util functions are implemented in place. Also mixing the camel case and snake case is unusual. I figured this was the easiest way to expose it without changing the existing places hash_to_field is used.

Should we add an example in readme highlighting that `randomPrivateKey` has an alternative option by passing random bytes into `hashToField`? We don't want to replace `randomPrivateKey` since it would become async and break the api.

What about if `keygen` is added later, then there'd be three different methods for generating a random private key.

### CODE REVIEW

**Comment by paulmillr** [comment]
> Should DST stay the same, or replace G2 with Fr, or some other replacement, or empty/blank?

We should let users pass custom `DST` to the method. Just like the spec says.

> Should L stay as 64 or should it be 48?

Same with `L`. Perhaps we could all parameters through an options hash? `{DST, F, p, m, L}` are the vars used in spec.

>I haven't added any tests for this change in functionality, I'm open to suggestions though.

Let's add three simple tests: hashing to `curve.p` (like we do today), hashing to curve.r, hashing to something else. See if you can find for test vectors from specs.

> Is it ok to refer be inconsistent in utils by including it as a one-liner hashToField: hash_to_field?

Yes. I've named it in snake_case for Googling purposes. It's easier to search on github for the spec-named function.

> Should we add an example in readme highlighting that randomPrivateKey has an alternative option by passing random bytes into hashToField

No. Low-level crypto should not concern users.

>What about if keygen is added later, then there'd be three different methods for generating a random private key.

No plans to add `keygen` to the repo. The repo should stay minimal and not add any additional primitives esp ones that are only used in eth.

**Comment by iancoleman** [comment]
> We should let users pass custom DST to the method. Just like the spec says.

Fair enough, but if users leave DST unspecified, should the default be the current `DST` or an empty string? I'm wondering whether we're introducing something that easily allows the user to make mistakes. I don't know if we are introducing a footgun, what do you think?

> Perhaps we could all parameters through an options hash? {DST, F, p, m, L} are the vars used in spec.

For my own future reference, these parameters are specified here: https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#name-hash_to_field-implementation

> Let's add three simple tests: hashing to curve.p (like we do today), hashing to curve.r, hashing to something else. See if you can find for test vectors from specs.

Sounds good. I'll look further for some specs for hash to scalar (no luck so far) and add some tests.

> No plans to add keygen to the repo. The repo should stay minimal and not add any additional primitives esp ones that are only used in eth.

No worries, that sounds fine. But a couple of points for discussion:

keygen is part of the bls signature spec, not specific to ethereum: https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-2.3

I agree it's probably better to stay minimal rather than introduce new cryptographic primitives.

keygen is pretty handy since it converts arbitrary bytes to a uniform value between `0` and `r`. It's probably better to have *some* way to do that (either hash_to_field or keygen) than leave it up to users to do outside of the library. Both these standardized ways have been well thought out, which is why I'm hoping to have access to one or the other (or both).

Downside of hash_to_field is uncertainty of which parameters to use, especially L and DST (hopefully the uncertainty can be resolved). Downside of keygen is the spec requires minimum 32 bytes so if passing in less than that it must throw an error (so it doesn't accept *any* arbitrary bytes, it's any bytes length 32 or more).

**Comment by iancoleman** [comment]
The comments in index.ts for https://github.com/iancoleman/noble-bls12-381/commit/641e53b330dd07d6a689a28ddc4a90850cb4c01a are quite detailed and explain how the changes match the spec.

`L` is computed so `CURVE.P` and `CURVE.r` give the correct value for their different bit lengths.

`DST` for hash to scalar is still something I'm researching. Same for test vectors. More to come hopefully soon.

**Comment by paulmillr** [comment]
> keygen is part of the bls signature spec

I did not realize this. It's great to have, but don't want to bring up dependency on hkdf (hkdf-sha256 etc).

**Comment by paulmillr** [comment]
> but if users leave DST unspecified, should the default be the current DST or an empty string

I think the default one should be the one this library uses. The reason is that DST specifies hash type, curve type etc. We only have bls12-381 here.

**Comment by iancoleman** [comment]
> I think the default one should be the one this library uses. The reason is that DST specifies hash type, curve type etc. We only have bls12-381 here.

Yeah I think this is right.

I was incorrectly thinking the `G2` in DST was referring to the output type, but it's referring to the broader way that bls is being used. `G2` in DST means publickey/signature is G1/G2, whereas `G1` in DST means publickey/signature is G2/G1. Like the difference between [min_pk vs min_sig](https://github.com/supranational/blst/blob/14bfc7a56c33c239d7f350238f030cf9072b77b6/bindings/rust/README.md#usage) in blst.

I can't find this explicitly stated in the spec (maybe it's there and I just can't recognize it) but I'm pretty sure DST is not about the output type, it's about the way the groups are used. So `BLS12381R1_XMD:SHA-256_SSWU_RO_` is probably nonsense. Would be good to definitely confirm it.

---

Regarding async, it looks like it all stems from sha256 being async. sha256 is a very fast operation, is there any particular reason for it being async?

I realize that changing it to not be async will change the api quite a lot (which is to avoided if possible) but it would greatly simplify things and would also enable randomPrivateKey to be able to use hash to scalar.

I'm not bothered either way, just curious.

**Comment by paulmillr** [comment]
The only reason sha256 is async is because we aim to use zero dependencies. Including sha256 implementation is at least 200 lines of code. Using the built-in one allows not to do it, but it's async as per browser standards

**Comment by iancoleman** [comment]
Some notes for my future reference:

There are some tests for hash_to_scalar in the bls12_381 rust crate

https://github.com/zkcrypto/bls12_381/blob/e501265cd36849a4981fe55e10dc87c38ee2213d/src/hash_to_curve/map_scalar.rs#L20

However these tests use expanded messages as the input, ie not `msg` but `expand_message_xmd(msg, DST, 48)`, so it doesn't directly translate into the implementation here.

It's also hidden behind a feature flag `experimental`. All hash_to_curve is experimental, not just hash_to_scalar.

**Comment by iancoleman** [comment]
The implementation passes the tests in the rust crate.

But the access to the scalar value as `result[0][0]` is pretty rubbish (eg [this line](https://github.com/iancoleman/noble-bls12-381/commit/b72716191f71ec4bfcb63137920501d93a87d941#diff-ec61822d929089017a892b4b047229377c9241f16b43252ab851ae39131cdf40R295) in the test). It's possibly better to create `utils.hashToScalar` as a wrapper around hash_to_field. What do you think?

**Comment by paulmillr** [comment]
I think you should use `Object.assign({}, htfDefaults, options)`.

**Comment by paulmillr** [comment]
@iancoleman no, we should keep it an array of arrays, because this way it's one api for everything. Users can then specify strict typescript types like `[[number, number]]`

**Comment by iancoleman** [comment]
I'm not seeing any more changes needed here.

I'm not especially attached to getting it merged considering it's still a pretty under-specified part of the spec, but I would use the changes if it were there. Let me know how you'd prefer to proceed, I'm happy to close or merge either way.

**Comment by paulmillr** [comment]
Let's merge it. Can you change the pr status?

**Comment by paulmillr** [comment]
Thank you.

**Pull request merged**
