### PR TITLE
[Point Compression] - Add methods to import points from their uncompressed form

### PR DESCRIPTION
**Pull request by RomarQ**
This PR aims to add support for importing points from their uncompressed representation.

https://docs.rs/bls12_381/0.4.0/bls12_381/struct.G1Affine.html#method.from_uncompressed
https://docs.rs/bls12_381/0.4.0/bls12_381/struct.G2Affine.html#method.from_uncompressed

Issue: #21

### CODE REVIEW

**Comment by paulmillr** [comment]
Please use one method `fromHex`. So, move the functionality from `fromUncompressed` to `if` clause of `fromHex`

**Comment by RomarQ** [comment]
> Please use one method `fromHex`. So, move the functionality from `fromUncompressed` to `if` clause of `fromHex`

Updated.

**Comment by paulmillr** [comment]
there is no need to have isCompressed argument in fromHex. We can detect the length automatically

**Comment by RomarQ** [comment]
True, fixing that :+1:

**Pull request merged**
